// <auto-generated />
using System;
using Eah.WorkSafety.WebApp.Back.Persistance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eah.WorkSafety.WebApp.Back.Persistance.Migrations
{
<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
    [DbContext(typeof(WorkSafetyContext))]
    [Migration("20221108213351_InitialCreate")]
    partial class InitialCreate
========
    [DbContext(typeof(WorkSafetyDbContext))]
    [Migration("20221205111614_mig1")]
    partial class mig1
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.AccidentAndNearMiss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccidentNearMissInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccidentNearMissNumber")
                        .HasColumnType("int");

                    b.Property<int>("AccidentOrNearMissTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdentifierUserId")
                        .HasColumnType("int");

========
            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.Accident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidentInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
                    b.Property<int>("LostDays")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RootCauseAnalysis")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
                    b.HasIndex("IdentifierUserId");

                    b.ToTable("AccidentAndNearMisses");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.AccidentAndNearMissTypes", b =>
========
                    b.ToTable("Accidents");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.ChronicDisease", b =>
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
                    b.ToTable("AccidentAndNearMissTypes");
========
                    b.ToTable("ChronicDiseases");
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.ContingencyPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("datetime2");

<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdentifierUserId")
========
                    b.Property<int>("CreatorUserId")
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanNumber")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
                    b.HasIndex("IdentifierUserId");
========
                    b.HasIndex("CreatorUserId");
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs

                    b.ToTable("ContingencyPlans");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDateOfEmployment")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.EmployeeAccident", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("AccidentId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "AccidentId");

                    b.HasIndex("AccidentId");

                    b.ToTable("EmployeeAccident");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.EmployeeChronicDisease", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ChronicDiseaseId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "ChronicDiseaseId");

                    b.HasIndex("ChronicDiseaseId");

                    b.ToTable("EmployeeChronicDisease");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.EmployeeNearMiss", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("NearMissId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "NearMissId");

                    b.HasIndex("NearMissId");

                    b.ToTable("EmployeeNearMiss");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.EmployeeOccupationDisease", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("OccupationDiseaseId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "OccupationDiseaseId");

                    b.HasIndex("OccupationDiseaseId");

                    b.ToTable("EmployeeOccupationDisease");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.Inconsistency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
========
                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
                    b.Property<int>("IdentifierUserId")
                        .HasColumnType("int");

========
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskScore")
                        .HasColumnType("int");

                    b.Property<bool>("RootCauseAnalysisRequirement")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
                    b.HasIndex("IdentifierUserId");
========
                    b.HasIndex("CreatorUserId");
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs

                    b.ToTable("Inconsistencies");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.NearMiss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("LostDays")
                        .HasColumnType("int");

                    b.Property<string>("NearMissInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NearMissNumber")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RootCauseAnalysis")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("NearMisses");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.OccupationDisease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
                    b.Property<int>("OccupationAndChronicDiseaseTypeId")
                        .HasColumnType("int");

========
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
                    b.HasIndex("OccupationAndChronicDiseaseTypeId");

                    b.ToTable("OccupationAndChronicDisease");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.OccupationAndChronicDiseaseTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OccupationAndChronicDiseaseTypes");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDateOfEmployment")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.PersonAccidentAndNearMiss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccidentAndNearMissId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccidentAndNearMissId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonAccidentAndNearMisses");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.PersonOccupationAndChronicDisease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DiagnosisDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OccupationAndChronicDiseaseId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OccupationAndChronicDiseaseId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonOccupationAndChronicDiseases");
========
                    b.ToTable("OccupationDiseases");
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.RiskAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("datetime2");

<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdentifierUserId")
========
                    b.Property<int>("CreatorUserId")
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevisionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
                    b.HasIndex("IdentifierUserId");
========
                    b.HasIndex("CreatorUserId");
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs

                    b.ToTable("RiskAssessments");
                });

<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.User", b =>
========
            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.Role", b =>
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.UserMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMissions");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.AccidentAndNearMiss", b =>
                {
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.AccidentAndNearMissTypes", "AccidentAndNearMissType")
                        .WithMany("AccidentNearMisses")
                        .HasForeignKey("AccidentOrNearMissTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.User", "Identifier")
                        .WithMany("AccidentNearMisses")
                        .HasForeignKey("IdentifierUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
========

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.ContingencyPlan", b =>
                {
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.User", "Identifier")
                        .WithMany("ContingencyPlans")
                        .HasForeignKey("IdentifierUserId")
========
            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.UserMission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "MissionId");

                    b.HasIndex("MissionId");

                    b.ToTable("UserMission");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.Accident", b =>
                {
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.User", "User")
                        .WithMany("Accidents")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.ContingencyPlan", b =>
                {
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.User", "User")
                        .WithMany("ContingencyPlans")
                        .HasForeignKey("CreatorUserId")
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.EmployeeAccident", b =>
                {
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.Accident", "Accident")
                        .WithMany("Employees")
                        .HasForeignKey("AccidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.Employee", "Employee")
                        .WithMany("Accidents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accident");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.EmployeeChronicDisease", b =>
                {
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.ChronicDisease", "ChronicDisease")
                        .WithMany("Employees")
                        .HasForeignKey("ChronicDiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.Employee", "Employee")
                        .WithMany("ChronicDiseases")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChronicDisease");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.EmployeeNearMiss", b =>
                {
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.Employee", "Employee")
                        .WithMany("NearMisses")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.NearMiss", "NearMiss")
                        .WithMany("Employees")
                        .HasForeignKey("NearMissId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("NearMiss");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.EmployeeOccupationDisease", b =>
                {
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.Employee", "Employee")
                        .WithMany("OccupationDiseases")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.OccupationDisease", "OccupationDisease")
                        .WithMany("Employees")
                        .HasForeignKey("OccupationDiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("OccupationDisease");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.Inconsistency", b =>
                {
<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.User", "Identifier")
                        .WithMany("Inconsistencies")
                        .HasForeignKey("IdentifierUserId")
========
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.User", "User")
                        .WithMany("Inconsistencies")
                        .HasForeignKey("CreatorUserId")
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.OccupationAndChronicDisease", b =>
                {
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.OccupationAndChronicDiseaseTypes", "OccupationAndChronicDiseaseType")
                        .WithMany("OccupationAndChronicDisease")
                        .HasForeignKey("OccupationAndChronicDiseaseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OccupationAndChronicDiseaseType");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.PersonAccidentAndNearMiss", b =>
                {
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.AccidentAndNearMiss", "AccidentAndNearMiss")
                        .WithMany("PersonAccidentAndNearMisses")
                        .HasForeignKey("AccidentAndNearMissId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.Person", "Person")
                        .WithMany("PersonAccidentAndNearMisses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccidentAndNearMiss");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.PersonOccupationAndChronicDisease", b =>
                {
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.OccupationAndChronicDisease", "OccupationAndChronicDisease")
                        .WithMany("PersonOccupationAndChronicDiseases")
                        .HasForeignKey("OccupationAndChronicDiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.Person", "Person")
                        .WithMany("PersonOccupationAndChronicDiseases")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OccupationAndChronicDisease");

                    b.Navigation("Person");
========
            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.NearMiss", b =>
                {
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.User", "User")
                        .WithMany("NearMisses")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.RiskAssessment", b =>
                {
<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.User", "Identifier")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("IdentifierUserId")
========
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.User", "User")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("CreatorUserId")
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.User", b =>
<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
                {
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.UserRole", "UserRole")
                        .WithMany("AppUsers")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.UserMission", b =>
                {
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.Mission", "Mission")
                        .WithMany("UserMissions")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.User", "User")
                        .WithMany("UserMissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.AccidentAndNearMiss", b =>
                {
                    b.Navigation("PersonAccidentAndNearMisses");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.AccidentAndNearMissTypes", b =>
========
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
                {
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

<<<<<<<< HEAD:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221108213351_InitialCreate.Designer.cs
            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.Mission", b =>
                {
                    b.Navigation("UserMissions");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.OccupationAndChronicDisease", b =>
                {
                    b.Navigation("PersonOccupationAndChronicDiseases");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.OccupationAndChronicDiseaseTypes", b =>
                {
                    b.Navigation("OccupationAndChronicDisease");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.Person", b =>
                {
                    b.Navigation("PersonAccidentAndNearMisses");

                    b.Navigation("PersonOccupationAndChronicDiseases");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.User", b =>
                {
                    b.Navigation("AccidentNearMisses");

                    b.Navigation("ContingencyPlans");

                    b.Navigation("Inconsistencies");

                    b.Navigation("RiskAssessments");

                    b.Navigation("UserMissions");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.UserRole", b =>
                {
                    b.Navigation("AppUsers");
                });
========
            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.UserMission", b =>
                {
                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.Mission", "Mission")
                        .WithMany("Users")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eah.WorkSafety.WebApp.Back.Core.Domain.User", "User")
                        .WithMany("Missions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.Accident", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.ChronicDisease", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.Employee", b =>
                {
                    b.Navigation("Accidents");

                    b.Navigation("ChronicDiseases");

                    b.Navigation("NearMisses");

                    b.Navigation("OccupationDiseases");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.Mission", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.NearMiss", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.OccupationDisease", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Eah.WorkSafety.WebApp.Back.Core.Domain.User", b =>
                {
                    b.Navigation("Accidents");

                    b.Navigation("ContingencyPlans");

                    b.Navigation("Inconsistencies");

                    b.Navigation("Missions");

                    b.Navigation("NearMisses");

                    b.Navigation("RiskAssessments");
                });
>>>>>>>> GoBackEntities:Eah.WorkSafety.WebApp.Back/Persistance/Migrations/20221205111614_mig1.Designer.cs
#pragma warning restore 612, 618
        }
    }
}
